name: Playwright Tests
on:
  repository_dispatch:
jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        uses: ./.github/actions/install-playwright-dependencies
      - name: Run Playwright tests
        run: npx playwright test
        env:
          TOKEN: ${{ secrets.TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
